### ISSUE TITLE
: net.sf.scuba.smartcards.CardServiceException: File not found, CAPDU exception

### ISSUE THREAD

**Issue by jonneymendoza** [alimertozdemir/EPassportNFCReader#6]
Hi i grabbed your project an ran it on my Samsung S8 device and i get an exception when i try to do the NFC conact part on the app using my british passport.

the MRZ scanning seems to work but not the NFC

Full stacktrace below

```
2021-01-13 16:30:23.885 25172-28874/com.alimert.passportreader W/MainActivity: net.sf.scuba.smartcards.CardServiceException: File not found, CAPDU = 00A4020C02011D, RAPDU = 6A82 (SW = 0x6A82: FILE NOT FOUND)
        at org.jmrtd.protocol.ReadBinaryAPDUSender.checkStatusWordAfterFileOperation(ReadBinaryAPDUSender.java:218)
        at org.jmrtd.protocol.ReadBinaryAPDUSender.sendSelectFile(ReadBinaryAPDUSender.java:79)
        at org.jmrtd.DefaultFileSystem.sendSelectFile(DefaultFileSystem.java:321)
        at org.jmrtd.DefaultFileSystem.getFileInfo(DefaultFileSystem.java:272)
        at org.jmrtd.DefaultFileSystem.getSelectedPath(DefaultFileSystem.java:129)
        at net.sf.scuba.smartcards.CardFileInputStream.<init>(CardFileInputStream.java:60)
        at org.jmrtd.PassportService.getInputStream(PassportService.java:595)
        at com.alimert.passportreader.ui.MainActivity$ReadTask.doInBackground(MainActivity.java:250)
        at com.alimert.passportreader.ui.MainActivity$ReadTask.doInBackground(MainActivity.java:223)
        at android.os.AsyncTask$3.call(AsyncTask.java:378)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)```

**Comment by alimertozdemir** [comment]
I think MRZ scanning is the problem. Sure it reads MRZ but extracted one of the passportNumber, birthDate and expirationDate values could be wrong. Could you please control these three values with writing log?
https://github.com/alimertozdemir/EPassportNFCReader/blob/b7828a21eb637ced07526d84e37df793d5482254/app/src/main/java/com/alimert/passportreader/ui/MainActivity.java#L211

**Comment by mahdi-salah** [comment]
After several successful times, I get the same error :

W/MainActivity: net.sf.scuba.smartcards.CardServiceException: Tag was lost.
        at net.sf.scuba.smartcards.IsoDepCardService.transmit(IsoDepCardService.java:123)
        at org.jmrtd.protocol.SecureMessagingAPDUSender.transmit(SecureMessagingAPDUSender.java:88)
        at org.jmrtd.protocol.ReadBinaryAPDUSender.sendSelectFile(ReadBinaryAPDUSender.java:73)
        at org.jmrtd.DefaultFileSystem.sendSelectFile(DefaultFileSystem.java:321)
        at org.jmrtd.DefaultFileSystem.getFileInfo(DefaultFileSystem.java:272)
        at org.jmrtd.DefaultFileSystem.getSelectedPath(DefaultFileSystem.java:129)
        at net.sf.scuba.smartcards.CardFileInputStream.<init>(CardFileInputStream.java:60)
        at org.jmrtd.PassportService.getInputStream(PassportService.java:595)
        at com.alimert.passportreader.ui.MainActivity$ReadTask.doInBackground(MainActivity.java:250)
        at com.alimert.passportreader.ui.MainActivity$ReadTask.doInBackground(MainActivity.java:223)
        at android.os.AsyncTask$3.call(AsyncTask.java:378)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)


I set the variables manually but I face the same issue:

        passportNumber = "AG1534337";
        expirationDate = "271212";
        birthDate = "020716";

**Comment by Redd1ntong** [comment]
I have the same issue, the problem isnt the MRZ, i am sure.
I am trying to build in my own app and i have the same issue, but if i do the same in your app, all works ok. In my app, if i try, it's works but without image. 
I am writing logs, all seems ok

**Comment by ashpakouski** [comment]
Hello, @alimertozdemir, @Redd1ntong, did you eventually find the reason of the issue? Am facing it too and I'm already out of ideas.

**Comment by YesidMarin** [comment]
Any solution?

**Comment by ElMostafaIdrassi** [comment]
@alimertozdemir This is not a MRZ issue. It looks like the app is trying to read EF 011D which corresponds to EF.CardSecurity, and it fails with 6A82 (File not found). Not all chips come with EF.CardSecurity, it is only mandatory if the chip supports PACE-CAM. The only EF that is mandatory for PACE is EF.CardAccess, which the app is not even using.
This results in the app selecting the applet without doing proper PACE beforehand.

The code in question is the following: https://github.com/alimertozdemir/EPassportNFCReader/blob/f9bbbc4cc856d42fdc5736d13246344245bbcd53/app/src/main/java/com/alimert/passportreader/ui/MainActivity.java#L248-L261

I think that adding the code to read EF.CardAccess will solve the issue.

**Comment by fuatebuzeynebKplus** [comment]
Did you find a solution to the problem??  I replaced this line with real data but still the same problem

 BACKeySpec bacKey = new BACKey("U2426****", "010***", "260***");

 @alimertozdemir @alimertozdemir @jonneymendoza @YesidMarin @Redd1ntong 

please if you have any idea or solution share with me

**Comment by mohamed00736** [comment]
Hello , Am having the same probleme , am scanning NFC of ID CARD and Passport very well , but withe Driver Licence its not working at all here is the error log : Error reading from card : 

``` 
net.sf.scuba.smartcards.CardServiceException: Error occured, CAPDU = 00A4040C07A0000002471001, RAPDU =6A86 (SW = 0x6A86: INCORRECT P1P2)at org.jmrtd.protocol.ReadBinaryAPDUSender.checkStatusWordAfterFileOperation(ReadBinaryAPDUSender.java:226)

at org.jmrtd.protocol.ReadBinaryAPDUSender.sendSelectApplet(ReadBinaryAPDUSender.java:58)

at org.jmrtd.PassportService.sendSelectApplet(PassportService.java:332)
```

**Comment by mohamed00736** [comment]
i made some progress , i created a class Called DriverLicnceService , its the same as PassportService but i only changed this  :   protected val APPLET_AID: ByteArray =  byteArrayOf(0xA0.toByte(), 0x00, 0x00, 0x02, 0x48, 0x02, 0x00) , now i can read the card , but the data seems a bit corrupted ,  some values are aempty , some fields looks they have some weird characters

**Comment by Bekdiyordev** [comment]
net.sf.scuba.smartcards.CardServiceException: Access to file denied, CAPDU = 00A4020C02011C, RAPDU = 6982 (SW = 0x6982: SECURITY STATUS NOT SATISFIED)
	at org.jmrtd.protocol.ReadBinaryAPDUSender.checkStatusWordAfterFileOperation(ReadBinaryAPDUSender.java:252)
	at org.jmrtd.protocol.ReadBinaryAPDUSender.sendSelectFile(ReadBinaryAPDUSender.java:90)
	at org.jmrtd.DefaultFileSystem.sendSelectFile(DefaultFileSystem.java:383)
	at org.jmrtd.DefaultFileSystem.getFileInfo(DefaultFileSystem.java:310)
	at org.jmrtd.DefaultFileSystem.getSelectedPath(DefaultFileSystem.java:157)
	at net.sf.scuba.smartcards.CardFileInputStream.<init>(CardFileInputStream.java:59)
	at org.jmrtd.PassportService.getInputStream(PassportService.java:651)
	at example.jllarraz.com.passportreader.utils.PassportNFC.<init>(PassportNFC.kt:251)
	at example.jllarraz.com.passportreader.utils.NFCDocumentTag.handleTag$lambda$0(NFCDocumentTag.kt:38)
	at example.jllarraz.com.passportreader.utils.NFCDocumentTag.$r8$lambda$5YoGVBNcj8IBOfSC73-JAEjloS0(Unknown Source:0)
	at example.jllarraz.com.passportreader.utils.NFCDocumentTag$$ExternalSyntheticLambda0.call(Unknown Source:8)
	at io.reactivex.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:44)
	at io.reactivex.Single.subscribe(Single.java:3666)
	at io.reactivex.internal.operators.single.SingleDoOnSubscribe.subscribeActual(SingleDoOnSubscribe.java:41)
	at io.reactivex.Single.subscribe(Single.java:3666)
	at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
	at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:307)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)
	
	
	I am getting this kind of error. How can I fix it? Who can solved this issue before?
